# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.box_check_update = true
  config.vm.hostname = "Key-Server.sshlab"

  config.vm.provider "hyperv" do |hv|
      hv.cpus = 2
      hv.maxmemory = "4096"
      hv.vmname = "Key-Server"
      hv.vm_integration_services = { 'time_synchronization' => true }
  end

  config.vm.provision "shell", path: "Setupscript.sh"
  config.vm.provision "file", source: "./keys", destination: "$HOME/ansible"
  config.vm.provision "file", source: "./hosts", destination: "$HOME/hosts"
  config.vm.provision "file", source: "./provisioning", destination: "$HOME/plays"
  config.vm.provision "file", source: "./interface", destination: "$HOME/eth0"
  config.vm.provision "shell", path: "Cleanup.sh"

end